"""
This type stub file was generated by pyright.
"""

"""Asyncio support for Motor, an asynchronous driver for MongoDB."""
__all__ = ["AsyncIOMotorClient"]

from typing import Any

AsyncIOMotorClient: Any
