# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Linux-Build-and-Run
on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main', 'development']

jobs:
  Linux-Build-and-Run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.6
      - run: |
          pip install -e .[dev]
          pip install coverage
      - name: Run Tests
        env:
          MONGOUSER: ${{ secrets.MONGOUSER }}
          MONGOPASSWORD: ${{ secrets.MONGOPASSWORD }}
        run: coverage run --source=g4 -m pytest -xs --log-cli-level=DEBUG tests/; coverage xml
